DROP TABLE IF EXISTS alunos;
DROP TABLE IF EXISTS professores;

CREATE TABLE alunos(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    senha NUMBER NOT NULL
);

CREATE TABLE professores(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    senha NUMBER NOT NULL
);